config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions'
}
  devise_for :customers, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "public/homes#top"
  get "about" => "public/homes#about"
  get "customers/my_page" => "public/customers#show"
  get "customers/:id/unsubscribe" => "public/customers#unsubscribe", as: "customers_unsubscribe"
  patch "customers/:id/withdrawal" => "public/customers#withdrawal", as: "customers_withdrawal"
  delete "cart_items/destroy_all" => "public/cart_items#destroy_all"
  get "orders/thanks" => "public/orders#thanks"
  post "orders/confirm" => "public/orders#confirm"
  post "orders" => "public/orders#create"


  namespace :public do
    resources :addresses, except: [:new, :show]
    resources :orders, only:[:new, :index, :show]
    resources :items, only:[:show, :index]
    resources :customers, only:[:edit, :update]
    resources :cart_items, only:[:index, :create, :update, :destroy]
  end  
    
  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    patch "order_details/:id" => "order_details#update", as: "order_detail"
  end
  get "admin/homes", to: "admin/homes#top"
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def full_address
    self.postal_code + self.address + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
         
  def full_name
    self.first_name + self.last_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord

end

 
 

app/models/item.rb
class Item < ApplicationRecord
  
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method:{ クレジットカード: 1, 銀行振込: 2 }

  enum status:{ payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
  
  def full_address
    self.postal_code + self.address + self.name
  end
  
  
  
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item

enum making_status:{ production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  
  def index
    @customers = Customer.page(params[:page])
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer.id)
    end
  end
  
  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, :encrypted_password, :postal_code, :address, :telephone_number, :is_active)
  end
  
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  
  def index
    @genre = Genre.new
    @genres = Genre.all
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :new
    end
  end
  
  
  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end
  
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    
    if params[:user_id].blank?
      @orders = Order.page(params[:page])
    else
      @orders = Order.where(customer_id: params[:user_id]).page(params[:page])
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
    @items = Item.page(params[:page])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
     @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    end
  end
  
  
  private
  
  def item_params
    params.require(:item).permit(:name, :image, :genre_id, :introduction, :price, :is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show
    @order = Order.find(params[:id])
    
    @sum = 0
    @order.order_details.each do |order_detail|
      sub_total = order_detail.item.price * order_detail.amount
      @sum += sub_total
    end
    @total = @sum
  end
  
  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to admin_order_path(@order.id)
    end
  end
  
  private
  def order_params
    params.require(:order).permit(:postal_code, :address, :name, :shipping_cost, :total_payment, :payment_method, :status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_homes_path
    when Customer
      root_path
    end
  end
  

  
  def after_sign_out_path_for(resource)
    case resource
    when :admin
    new_admin_session_path 
    when :customer
      root_path
    end
  end
  
  

  protected

  
   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:first_name_kana,:last_name_kana, :email, :postal_code,:address,:telephone_number])
   end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
  
  def number_to_currency(price)
    "#{￥price.to_s(:delimited, delimiter: ',')}"
  end
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def number_to_currency(price)
    "#{￥price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="row col-4">
    <h5 class="my-4 mx-4 px-3 text-dark bg-light"><%= @customer.first_name %><%= @customer.last_name %>さんの会員情報編集</h5>
  </div>
  
  <div class="form-body mt-4 offset-1">
    <%= form_with model: @customer, url: admin_customer_path, local:true do |f| %>
      <div class="form-group row">
        <label class="col-3 control-label col-from-label">会員ID</label>
        <label><%= @customer.id %></label>
      </div>
      <div class="form-group row">
        <label class="col-3 control-label col-from-label">氏名</label>
        <%= f.text_field :first_name , class:"form-control pl-0 mr-4 col-3" %>
        <%= f.text_field :last_name, class:"form-control pl-0 col-3" %>
      </div>
      <div class="form-group row">
        <label class="col-3 control-label col-from-label">フリガナ</label>
        <%= f.text_field :first_name_kana, class:"form-control pl-0 mr-4 col-3" %>
        <%= f.text_field :last_name_kana, class:"form-control pl-0 col-3" %>
      </div>
      <div class="form-group row">
        <label class="col-3 control-label col-from-label">郵便番号</label>
        <%= f.text_field :postal_code, class:"form-control overflow-auto pl-0 col-3" %>
      </div>
      <div class="form-group row">
        <label class="col-3 control-label col-from-label">住所</label>
        <%= f.text_field :address, class:"form-control pl-0 col-7" %>
      </div>
      <div class="form-group row">
        <label class="col-3 control-label col-from-label">電話番号</label>
        <%= f.text_field :telephone_number, class:"form-control pl-0 col-3" %>
      </div>
      <div class="form-group row">
        <label class="col-3 control-label col-from-label">メールアドレス</label>
        <%= f.text_field :email, class:"form-control pl-0 col-3" %>
      </div>
      <div class="form-group row">
        <label class="col-3 control-label col-from-label">会員ステータス</label>
        <div class="custom-control custom-radio pl-0">
          <%= f.radio_button :is_active, 'true' %>
          <%= f.label :is_active, '有効', value: true %>
        </div>
        <div class="custom-control custom-radio">
          <%= f.radio_button :is_active, 'false' %>
          <%= f.label :is_active, '退会', value: false %>
        </div>
      </div>
      <div class="form-group offset-3">
        <%= f.submit '変更を保存', class:"btn btn-lg btn-success mt-4" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row offset-1">
    <div>
      <h5 class="my-4 px-3 text-dark bg-light">会員一覧</h5>
    </div>
    </div>
  </div>
  <div class="row col-8 offset-2">
    <table class="table table-inverse">
      <thead class="bg-light">
        <tr>
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody class="solid">
        <% @customers.each do |customer| %>
        <tr>
          <td><%= customer.id %></td>
          <td>
            <%= link_to admin_customer_path(customer.id) do %>
              <%= customer.first_name %><%= customer.last_name %>
            <% end %>
          </td>
          <td><%= customer.email %></td>
          <td><%= customer.is_active == true ? "有効" : "退会" %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row d-flex justify-content-center">
    <span style="padding: 0 10px"><%= paginate @customers %></span>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row mt-2">
    <h5 class="col-3 mt-4 ml-5 mb-4 bg-light text-center"><strong><%= @customer.first_name %><%= @customer.last_name %>さんの会員詳細</strong></h5>
  </div>
  <div class="row mt-3 ml-2">
    <div class="form-body col-9 ml-3">
      <table class="table table-borderless mb-0">
        <tr>
          <td style="width: 30%;" class="py-2"><label>会員ID</label></td>
          <td class="py-2"><label><%= @customer.id %></label></td>
        </tr>
        <tr>
          <td class="py-2"><label>氏名</label></td>
          <td class="py-2"><label><%= @customer.first_name %></label>&emsp;<label><%= @customer.last_name %></label></td>
        </tr>
        <tr>
          <td class="py-2"><label>フリガナ</label></td>
          <td class="py-2"><label><%= @customer.first_name_kana %></label>&emsp;<label><%= @customer.last_name_kana %></label></td>
        </tr>
        <tr>
          <td class="py-2"><label>郵便番号</label></td>
          <td class="py-2"><label><%= @customer.postal_code %></label></td>
        </tr>
        <tr>
          <td class="py-2"><label>住所</label></td>
          <td class="py-2"><label><%= @customer.address %></label></td>
        </tr>
        <tr>
          <td class="py-2"><label>電話番号</label></td>
          <td class="py-2"><label><%= @customer.telephone_number %></label></td>
        </tr>
        <tr>
          <td class="py-2"><label>メールアドレス</label></td>
          <td class="py-2"><label><%= @customer.email %></label></td>
        </tr>
        <tr>
          <td class="py-2"><label>会員ステータス</label></td>
          <td class="py-2"><label><%= @customer.is_active == true ?  "有効" : "退会" %></label></td>
        </tr>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-2 offset-3"><%= link_to "編集する", edit_admin_customer_path, class: 'btn btn-md btn-success px-3' %></div>
    <div class="justify-content-center"><%= link_to "注文履歴一覧を見る", admin_homes_path(user_id: @customer.id), class: ' btn btn-md btn-primary px-4' %></div>
  </div>
    
  
</div>

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row">
    <h5 class="col-2 m-4 bg-light text-center">ジャンル編集</h5>
  </div>
  <div class="row">
    <%= form_with model: @genre, url: admin_genre_path, class: "d-flex flex-row align-items-center my-4", local:true do |f| %>
      <div class="col-3">
        <p class="m-0">ジャンル名</p>
      </div>
      <div class="col-6">
        <%= f.text_field :name, class:"form-control", placeholder:"ジャンル名" %>
      </div>
      <div class="col-4 text-right">
        <%= f.submit '変更を保存', class:"btn btn-md px-4 btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row col-10">
    <h5 class="col-3 m-4 bg-light text-center">ジャンル一覧・追加</h5>
  </div>
  <div class="row col-10">
    <%= form_with model: @genre, url: admin_genres_path, class: "d-flex flex-row align-items-center my-4", local:true do |f| %>
      <div class="col-3">
        <p class="m-0">ジャンル名</p>
      </div>
      <div class="col-6">
        <%= f.text_field :name, class:"form-control", placeholder:"ジャンル名" %>
      </div>
      <div class="col-4 text-right">
        <%= f.submit '新規登録', class:"btn btn-md px-4 btn-success" %>
      </div>
    <% end %>
  </div>
  
  <div class="row">
    <table class="table table-inverse mt-4 col-5">
      <thead class="bg-light">
        <tr>
          <th class=" p-2 text-center">ジャンル</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody class="solid">
        <% @genres.each do |genre| %>
        <tr>
          <td class="pt-4">
            <span><%= genre.name %></span>
          </td>
          <td>
            <%= link_to "編集する", edit_admin_genre_path(genre.id), class: 'nav-link btn btn-success px-1 btn-ms' %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/homes/top.html.erb
<div class="container">
  <div class="row col-10 offset-1">
    <h5 class="my-4 px-3 text-dark bg-light">注文履歴一覧</h5> 
    <table class="table table-inverse">
        <thead class="bg-light">
            <tr>
              <th style="width:25%;">購入日時</th>
              <th>購入者</th>
              <th>注文個数</th>
              <th>注文ステータス</th>
            </tr>
        </thead>
        <tbody class="solid">
          <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order.id) do %>
                <u><%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %></u>
              <% end %>
            </td>
            <td><%= order.customer.first_name %><%= order.customer.last_name %></td>
            <td>
              <% sum = 0 %>
              <% order.order_details.each do |order_detail| %>
                <% order_detail.amount %>
                <% sum += order_detail.amount %>
              <% end %>
              <%= sum %>
            </td>
            <td><%= order.status_i18n %></td>
          </tr>
          <% end %>
        </tbody>
    </table>
  </div>
  <div class="row d-flex justify-content-center">
    <span style="padding: 0 10px"><%= paginate @orders %></span>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row offset-1">
    <h5 class="my-4 mx-4 px-3 text-dark bg-light">商品編集</h5>
  </div>
  
  <div class="form-body mt-4 offset-2">
    <%= form_with model: @item, url: admin_item_path, local:true do |f| %>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label">商品画像</label>
        <div class="item_image_btn">
          <%= f.attachment_field :image,  id: "file" %>
        </div>
        <div id="img_field" onClick="$('#file').click()" >
          <p>ファイルを選択</p>
        </div>
        <span class="p-2">選択されていません</span>
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label text-left">商品名</label>
        <%= f.text_field :name, class:"form-control col-5", placeholder:"商品名" %>
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label text-left">商品説明</label>
        <%= f.text_area :introduction, class:"form-control overflow-auto col-5", rows:"3", placeholder:"ここに説明文を記述します" %>
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label text-left">ジャンル</label>
        <div class="col-5 px-0">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: '--選択してください--'}, class: 'form-select pl-0 form-control' %>
        </div>    
      </div>
      
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label text-left">税抜価格</label>
        <%= f.text_field :price, class:"form-control col-5", placeholder:"1000" %><span class="pt-2 pl-1">円</span>
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pr-0 control-label col-from-label">販売ステータス</label>
        <div class="custom-control pl-0 custom-radio">
          <%= f.radio_button :is_active, 'true' %>
          <%= f.label :is_active, '販売中', value: true %>
        </div>
        <div class="custom-control custom-radio">
          <%= f.radio_button :is_active, 'false' %>
          <%= f.label :is_active, '販売停止中', value: false %>
        </div>
      </div>
      <div class="form-group row offset-3">
        <%= f.submit '変更を保存', class:"btn-new mt-4" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row col-10 offset-1">
    <div class="">
      <h5 class="my-4 mx-4 px-3 text-dark bg-light">商品一覧</h5>
    </div>
    <div class="ml-auto mt-3">
      <div class="nav-item">
        <a href="items/new" class="btn-circle-3d">+</a>
      </div>
    </div>
  </div>
  <div class="row col-10 offset-1">
    <table class="table table-inverse">
      <thead class="bg-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody class="solid">
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <%= link_to admin_item_path(item.id) do %>
              <u><%= item.name %></u>
            <% end %>
          </td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td><span class="colored"><%= item.is_active == true ? "販売中" : "販売停止中" %></span></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row d-flex justify-content-center">
    <span><u><%= paginate @items %></u></span>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  
  <div class="row">
    <h5 class="my-4 mx-4 px-3 text-dark bg-light">商品新規登録</h5>
  </div>
  
  <div class="form-body mt-4 offset-2">
    <%= form_with model: @item, url: admin_items_path, local:true do |f| %>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label">商品画像</label>
        <div class="item_image_btn">
          <%= f.attachment_field :image,  id: "file" %>
        </div>
        <div id="img_field" onClick="$('#file').click()" >
          <p>ファイルを選択</p>
        </div>
        <span class="p-2">選択されていません</span>
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label text-left">商品名</label>
        <%= f.text_field :name, class:"form-control col-5", placeholder:"商品名" %>
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label text-left">商品説明</label>
        <%= f.text_area :introduction, class:"form-control overflow-auto col-5", rows:"3", placeholder:"ここに説明文を記述します" %>
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label text-left">ジャンル</label>
        <div class="col-5 px-0">
          <%= f.collection_select :genre_id, Genre.all, :id, :name, {prompt: '--選択してください--'}, class: 'form-select pl-0 form-control' %>
        </div>  
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pt-1 control-label col-from-label text-left">税抜価格</label>
        <%= f.text_field :price, class:"form-control col-5", placeholder:"1000" %><span class="pt-2 pl-1">円</span>
      </div>
      <div class="form-group row">
        <label class="col-2 mr-3 pr-0 control-label col-from-label">販売ステータス</label>
        <div class="custom-control pl-0 custom-radio">
          <%= f.radio_button :is_active, 'true' %>
          <%= f.label :is_active, '販売中', value: true %>
        </div>
        <div class="custom-control custom-radio">
          <%= f.radio_button :is_active, 'false' %>
          <%= f.label :is_active, '販売停止中', value: false %>
        </div>
      </div>
      <div class="form-group row offset-3">
        <%= f.submit '新規登録', class:"btn-new mt-4" %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row mt-2">
    <div class="offset-1" >
      <h5 class="mt-4 mx-5 mb-5 px-3  bg-light text-center"><strong>商品詳細</strong></h5>
    </div>
  </div>
  <div class="row mt-4 justify-content-center">
    <div class="col-3 pt-1 px-0">
        <%= attachment_image_tag @item, :image, size: "230x180", fallback: "no_image.jpg" %>
    </div>
    <div class="form-body col-7 ml-3">
      <table class="table table-sm table-borderless">
        <tr>
          <td style="width:30%;"><label>商品名</label></td>
          <td><label><%= @item.name %></label></td>
        </tr>
         <tr>
           <td><label>商品説明</label></td>
           <td><text><%= @item.introduction %></text></td>
         </tr>
         <tr>
           <td><label>ジャンル</label></td>
           <td><label><%= @item.genre.name %></label></td>
         </tr>
         <tr>
           <td><label>税込価格<br>(税抜価格)</label></td>
           <td><label><%= (@item.price * 1.1).round(2).ceil %></label> <label>(<%= @item.price %>)</label> 円</td>
         </tr>
         <tr>
           <td><label>販売ステータス</label></td>
           <td><label><%= @item.is_active == true ?  "販売中" : "販売停止中" %></label></td>
         </tr>
      </table>
    </div>
  </div>
  <div class="row justify-content-center">
    <%= link_to "編集する", edit_admin_item_path, class: 'btn btn-lg btn-success px-4 mt-4' %>
  </div>
    
  
</div>

app/views/admin/orders/show.html.erb
<div class="conteiner">
  <div class="row col-3 offset-1">
    <h5 class="mt-5 mx-4 px-3 text-dark bg-light">注文履歴詳細</h5>
  </div>
  
  <div class="row col-10 ml-3">
    <div class="col-10">
      <table class="table table-borderless mt-2">
        <tr>
          <td style="width:15%;"><strong>購入者</strong></td>
          <td class="pl-1">
            <%= link_to admin_customer_path(@order.customer.id) do %>
              <u><%= @order.customer.first_name %>&nbsp;<%= @order.customer.last_name %></u>
            <% end %>
          </td>
        </tr>
        <tr>
          <td><strong>注文日</strong></td>
          <td class="pl-1"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
        </tr>
        <tr>
          <td><strong>配送先</strong></td>
          <td class="p-1">〒<%= @order.postal_code %>&nbsp;<%= @order.address %><br><%= @order.name %></td>
        </tr>
        <tr>
          <td><strong>支払方法</strong></td>
          <td class="px-1"><%= @order.payment_method %></td>
        </tr>
        <tr>
          <td><strong>注文ステータス</strong></td>
          <td>
            <%= form_with model: @order, url: admin_order_path(@order.id), local:true do |f| %>
            　<%#= f.select :status, Order.statuses.keys.map {|k| [I18n.t("enum.order.status.#{k}"), k]}, class: "" %>
            　<%= f.select :status, Order.statuses_i18n.invert %> 
              <%= f.submit '更新', class:"btn btn-sm btn-success ml-2 px-1 py-1" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
    

  <div class="row col-12 ml-3">
    <div class="col-8">
      <table class="table table-borderless border-top border-bottom">
        <thead class="bg-light">
          <tr>
            <th style="width:50%;">商品名</th>
            <th style="width:14%;">単価(税込)</th>
            <th style="width:8%;">数量</th>
            <th style="width:8%;">小計</th>
            <th style="width:20%;">製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order.order_details.each do |order_detail| %>
            <tr>
            　<td class="px-1"><%= order_detail.item.name %></td>
              <td class="px-1"><%= order_detail.item.price %></td>
              <td class="px-1"><%= order_detail.amount %></td>
              <td class="px-1"><%= order_detail.item.price * order_detail.amount %></td>
              <td class="px-1">
                <%= form_with model: order_detail, url: admin_order_detail_path(order_detail), local:true do |f| %>
                　<%#= f.select :making_status, OrderDetail.making_statuses.keys.map{|k| [I18n.t("enum.order_detail.making_status.#{k}"), k]}, class: "" %>
                　<%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %> 
                  <%= f.submit '更新', class:"btn btn-sm btn-success ml-2 px-1 py-1" %>
                <% end %>  
              </td>
            </tr>
          <% end %>
        </tbody>
      </table> 
    </div>
    
    <div class="col-4 mt-5">
      <table class="table table-borderless mt-5 ml-4 mb-auto">
        <tr>
          <td class="p-1" style="width:30%;"><strong>商品合計</strong></td>
          <td class="p-1"><%= @total.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <td class="p-1"><strong>配送料</strong></td>
          <td class="p-1"><%= @order.shipping_cost.to_s(:delimited, delimiter: ',') %>円</td>
        </tr>
        <tr>
          <td class="p-1"><strong>請求⾦額合計</strong></td>
          <td class="p-1"><strong><%= @order.total_payment.to_s(:delimited, delimiter: ',') %>円</strong></td>
        </tr>  
      </table>
    </div> 
  </div>
</div>