config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
  sessions:      'admins/sessions'
}
  devise_for :customers, controllers: {
  sessions:      'publics/sessions',
  passwords:     'publics/passwords',
  registrations: 'publics/registrations'
}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "public/homes#top"
  get "about" => "public/homes#about"
  get "customers/my_page" => "public/customers#show"
  get "customers/:id/unsubscribe" => "public/customers#unsubscribe", as: "customers_unsubscribe"
  patch "customers/:id/withdrawal" => "public/customers#withdrawal", as: "customers_withdrawal"
  delete "cart_items/destroy_all" => "public/cart_items#destroy_all"
  get "orders/thanks" => "public/orders#thanks"
  post "orders/confirm" => "public/orders#confirm"
  post "orders" => "public/orders#create"


  namespace :public do
    resources :addresses, except: [:new, :show]
    resources :orders, only:[:new, :index, :show]
    resources :items, only:[:show, :index]
    resources :customers, only:[:edit, :update]
    resources :cart_items, only:[:index, :create, :update, :destroy]
  end  
    
  namespace :admin do
    resources :items, except: [:destroy]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    patch "order_details/:id" => "order_details#update", as: "order_detail"
  end
  get "admin/homes", to: "admin/homes#top"
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  def full_address
    self.postal_code + self.address + self.name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         
         
  def full_name
    self.first_name + self.last_name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
end

app/models/home.rb
class Home < ApplicationRecord

end

 
 

app/models/item.rb
class Item < ApplicationRecord
  
  
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  attachment :image
  
  
end

app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method:{ クレジットカード: 1, 銀行振込: 2 }

  enum status:{ payment_waiting: 0, payment_confirmation: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
  
  def full_address
    self.postal_code + self.address + self.name
  end
  
  
  
  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  
  belongs_to :order
  belongs_to :item

enum making_status:{ production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    
    if params[:user_id].blank?
      @orders = Order.page(params[:page])
    else
      @orders = Order.where(customer_id: params[:user_id]).page(params[:page])
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  
  def index
    @items = Item.page(params[:page])
  end
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
     @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    end
  end
  
  
  private
  
  def item_params
    params.require(:item).permit(:name, :image, :genre_id, :introduction, :price, :is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_homes_path
    when Customer
      root_path
    end
  end
  

  
  def after_sign_out_path_for(resource)
    case resource
    when :admin
    new_admin_session_path 
    when :customer
      root_path
    end
  end
  
  

  protected

  
   def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name,:first_name_kana,:last_name_kana, :email, :postal_code,:address,:telephone_number])
   end
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
  
  def number_to_currency(price)
    "#{￥price.to_s(:delimited, delimiter: ',')}"
  end
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def number_to_currency(price)
    "#{￥price.to_s(:delimited, delimiter: ',')}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <nav class="navbar navbar-expand-lg navbar-light d-flex">
        <a class="navbar-brand mt-3" href="/">
          <%= image_tag "linkedin_banner_image_1.png", size:'160x80' %>
        </a>
        <div class="ml-auto">
          <ul class="nav nav-pills">
            <% if customer_signed_in? %>
            <div class="row mt-5 mr-4">
              <li class="nav-item mx-2 px-2"><%= link_to "マイページ", customers_my_page_path, class: 'btn btn-default active' %></li>
              <li class="nav-item mx-2 px-2"><%= link_to "商品一覧",public_items_path, class: 'btn btn-default active' %></li>
              <li class="nav-item mx-2 px-2"><%= link_to "カート", public_cart_items_path, class: 'btn btn-default active' %></li>
              <li class="nav-item mx-2 px-2"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'btn btn-default active' %></li>
            </div>
            <% elsif admin_signed_in? %>
            <div class="row col-9 mt-3 offset-4">
              <li class="nav-item px-2"><%= link_to "商品一覧", admin_items_path, class: 'btn btn-default-admin active' %></li>
              <li class="nav-item px-2"><%= link_to "会員一覧",admin_customers_path, class: 'btn btn-default-admin active' %></li>
              <li class="nav-item px-2"><%= link_to "注文履歴一覧", admin_homes_path, class: 'btn btn-default-long active' %></li>
              <li class="nav-item px-2"><%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-default-long active'%></li>
              <li class="nav-item px-2"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'btn btn-default-logout active' %></li>
            </div>
            <div class="row mt-3 mr-3 col-5  offset-8">
              <% if admin_signed_in? %>
                <form class="form-inline">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search">
                      <span class="input-group-btn">
                        <button class="btn search"><i class="fas fa-search fa-flip-horizontal"></i></button>
                      </span>
                    </input>
                  </div>
                </form>
              <% end %>
            </div>
            <% else %>
            <div class="row mt-5 mr-4">
              <li class="nav-item mx-2 px-2"><%= link_to "About", about_path, class: 'btn btn-default-about text-centr active' %></li>
              <li class="nav-item mx-2 px-2"><%= link_to "商品一覧", public_items_path, class: 'btn btn-default active' %></li>
              <li class="nav-item mx-2 px-2"><%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-default active' %></li>
              <li class="nav-item mx-2 px-2"><%= link_to "ログイン", new_customer_session_path, class: 'btn btn-default active' %></li>
            </div>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    
    <main class="mb-auto">
      <%= yield %>
    </main>
    
    <footer class="footer"></footer>
  </body>
</html>